version: '3.8'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000

  graphite-statsd:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126
      - 8080:80